version: "3"
services: 
  movieapp:
    image: movieapp
    container_name: movieapp
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file: .env.development
    command: npm run start:dev
    volumes: 
      - .:/opt/node_app/app:delegated
      - ./package.json:/opt/node_app/package.json
      - ./package-lock.json:/opt/node_app/package-lock.json
    restart: always
    networks:
      - default
    ports:
      - "3000:3000"
    links:
      - moviedb
    depends_on:
      - moviedb
  moviedb:
    image: postgres:12.2
    container_name: moviedb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: movies_development
    volumes:
      - moviedb:/var/lib/postgresql/data
    networks:
      - default
volumes:
  moviedb: